// Generated by CoffeeScript 1.3.3

(function(root) {
  return root.SimpleMachine = (function() {

    function SimpleMachine(state, transitions) {
      this.state = state;
      this.transitions = transitions != null ? transitions : {};
      this.callbacks = [];
    }

    SimpleMachine.prototype.on = function(event, callback, context) {
      if (context != null) {
        callback = function() {
          return callback.call(context);
        };
      }
      if (this.callbacks[event] != null) {
        this.callbacks[event].push(callback);
      } else {
        this.callbacks[event] = [callback];
      }
      return this;
    };

    SimpleMachine.prototype.trigger = function(event) {
      var callback, callbacks, _i, _len, _ref, _ref1;
      if (event === 'any' || (((_ref = this.transitions) != null ? (_ref1 = _ref[event]) != null ? _ref1[this.state] : void 0 : void 0) != null)) {
        return false;
      }
      this.state = this.transitions[event][this.state];
      callbacks = this.callbacks[this.state] + this.callbacks['any'];
      for (_i = 0, _len = callbacks.length; _i < _len; _i++) {
        callback = callbacks[_i];
        callback();
      }
      return true;
    };

    return SimpleMachine;

  })();
})(typeof 'exports' === 'undefined' ? window : exports);
