// Generated by CoffeeScript 1.3.3

(function(root) {
  return root.SimpleMachine = (function() {

    function SimpleMachine(state, transitions, callbacks) {
      this.state = state;
      this.transitions = transitions != null ? transitions : {};
      this.callbacks = callbacks != null ? callbacks : {};
    }

    SimpleMachine.prototype.on = function(event, callback, context) {
      if (context != null) {
        callback = function() {
          return callback.call(context);
        };
      }
      this.callbacks[event] = [callback].concat(this.callbacks[event]);
      return this;
    };

    SimpleMachine.prototype.trigger = function(event) {
      var callback, _i, _len, _ref, _ref1;
      if ((((_ref = this.transitions[event]) != null ? _ref[this.state] : void 0) != null) && event !== 'all') {
        this.state = this.transitions[event][this.state];
        _ref1 = [this.callbacks.all].concat(this.callbacks[this.state]);
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          callback = _ref1[_i];
          if (typeof callback === "function") {
            callback();
          }
        }
        return true;
      } else {
        return false;
      }
    };

    return SimpleMachine;

  })();
})(typeof 'exports' === 'undefined' ? window : exports);
